import { FavorisProvider, ImgsProvider } from "./comps/comps";
import "./styles.css";

export const metadata = {
  title: 'memes generator',
  description: 'Generated by Next.js',
  icons: { icon: '/logo_bg.png' },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ImgsProvider>
          <FavorisProvider>
            {children} 
          </FavorisProvider>
        </ImgsProvider>
      </body>
    </html>
  )
}
